# Generated by Django 6.0.3 on 2026-03-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='user_name',
            new_name='student_reg_no',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='text',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='grid',
        ),
        migrations.AddField(
            model_name='clue',
            name='question',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clue',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clue',
            name='direction',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
