# Generated by Django 6.0.3 on 2026-03-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_name_attempt_student_reg_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts_list', to='api.puzzle'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='student_reg_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='status',
            field=models.CharField(default='Not Started', max_length=50),
        ),
    ]
