# Generated by Django 6.0 on 2026-03-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_teacher_puzzle_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='completion_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='solved_words_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='validation_mode',
            field=models.CharField(choices=[('instant', 'Instant Validation'), ('on_submit', 'Validate On Submit')], default='on_submit', max_length=20),
        ),
    ]
