# Generated by Django 6.0 on 2026-03-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attempt_completion_time_attempt_solved_words_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='hint_letters_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='hint_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='hint_words_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='result_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='difficulty',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=50),
        ),
    ]
