# api/urls.py
from django.urls import path
from .views import (
    puzzle_list,
    submit_puzzle,
    leaderboard,
    check_answer,
    stats,
    login,
    create_puzzle,
    add_clues,
    publish_puzzle,
    puzzle_preview,
    update_clue,
    delete_clue,
    regenerate_layout,
    archive_puzzle,
    delete_puzzle,
    leaderboard_by_puzzle,
    puzzle_analytics,
    analytics,
    student_history,
    reveal_hint,
    printable_export,
    generate_from_document,
    admin_teachers,
    admin_teacher_detail,
    admin_students,
    teacher_students,
    upload_students_csv,
    reset_student_password,
    delete_student,
)

urlpatterns = [
    path('login/', login, name='login'),
    path('puzzles/', puzzle_list, name='puzzle_list'),
    path('puzzles/<int:puzzle_id>/preview/', puzzle_preview, name='puzzle_preview'),
    path('puzzles/<int:puzzle_id>/regenerate/', regenerate_layout, name='regenerate_layout'),
    path('puzzles/<int:puzzle_id>/archive/', archive_puzzle, name='archive_puzzle'),
    path('puzzles/<int:puzzle_id>/', delete_puzzle, name='delete_puzzle'),
    path('puzzles/<int:puzzle_id>/export/', printable_export, name='printable_export'),
    path('puzzles/create/', create_puzzle, name='create_puzzle'),
    path('puzzles/add-clues/', add_clues, name='add_clues'),
    path('puzzles/generate-from-document/', generate_from_document, name='generate_from_document'),
    path('puzzles/clues/<int:clue_id>/update/', update_clue, name='update_clue'),
    path('puzzles/clues/<int:clue_id>/delete/', delete_clue, name='delete_clue'),
    path('puzzles/publish/', publish_puzzle, name='publish_puzzle'),
    path('submit/', submit_puzzle, name='submit_puzzle'),
    path('leaderboard/', leaderboard, name='leaderboard'),
    path('leaderboard/<int:puzzle_id>/', leaderboard_by_puzzle, name='leaderboard_by_puzzle'),
    path('analytics/<int:puzzle_id>/', puzzle_analytics, name='puzzle_analytics'),
    path('analytics/', analytics, name='analytics'),
    path('history/', student_history, name='student_history'),
    path('check/', check_answer, name='check_answer'),
    path('hint/', reveal_hint, name='reveal_hint'),
    path('stats/', stats, name='stats'),
    path('admin/teachers/', admin_teachers, name='admin_teachers'),
    path('admin/teachers/<str:teacher_id>/', admin_teacher_detail, name='admin_teacher_detail'),
    path('admin/students/', admin_students, name='admin_students'),
    path('students/', teacher_students, name='teacher_students'),
    path('students/upload/', upload_students_csv, name='upload_students_csv'),
    path('students/<int:student_id>/reset-password/', reset_student_password, name='reset_student_password'),
    path('students/<int:student_id>/', delete_student, name='delete_student'),
]
